---
language: objective-c
rvm:
- 1.9.3
before_install:
  - sudo mkdir -p /Users/travis/Library/RubyMotion/build
  - sudo chmod -R 664 /Users/travis/Library/RubyMotion/build
  - bundle install && rake pod:install
script: rake spec
